bases:
- ../../base

commonLabels:
  env: production

# Increase the base deployment replica count, and use a fixed image tag
patches:
  - target:
      kind: Deployment
      name: roshambo-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 4
  - target:
      kind: Deployment
      name: roshambo-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1