namespace: rps-game

backend:
  image: quay.io/rhdevelopers/roshambo-backend:latest
  # Do not change. Backend is not designed to scale horizontally.
  repicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

frontend:
  image: quay.io/rhdevelopers/roshambo-frontend:latest
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"